### ISSUE TITLE
project not working

### ISSUE THREAD

**Issue by HasanAJ** [viku85/CodeSample#1]
I get the below when I run the project

NullReferenceException: Object reference not set to an instance of an object.
MyProject.Web.Controllers.HomeController.Index() in HomeController.cs
+
            MyProjectUnitOfWork.BookRepository.Create(new Model.DataModel.Book
lambda_method(Closure , object , Object[] )

**Comment by viku85** [comment]
It happened due to missed push. Changes should work fine.
Also, it was informed on the blog too.
https://vikutech.blogspot.in/2017/03/unit-of-work-injection-through-asp-net-core-dependency-injection.html
